# Generated by Django 4.2.16 on 2024-11-07 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technique',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/technique'),
        ),
    ]
